# Copyright (C) 2022 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

# A reference configuration file containing all possible ORT configuration options. Some of those options are mutually
# exclusive, so this file is only used to show all options and to validate the configuration.

ort:
  allowedProcessEnvironmentVariableNames:
    - PASSPORT
    - USER_HOME
  deniedProcessEnvironmentVariablesSubstrings:
    - PASS
    - SECRET
    - TOKEN
    - USER

  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  # Force overwriting of any existing output files.
  forceOverwrite: true

  licenseFilePatterns:
    licenseFilenames: ['license*']
    patentFilenames: ['patents']
    rootLicenseFilenames: ['readme*']

  # Package configurations have to be unique by ID and provenance. Ensure that different providers do not provide
  # configurations for the same package, see https://github.com/oss-review-toolkit/ort/issues/6972 for details.
  # packageConfigurationProviders:
  # - type: DefaultDir
  # - type: Dir
  #   id: SomeConfigDir
  #   options:
  #     path: '/some-path/'
  #     mustExist: true
  # - type: OrtConfig

  # Package curation providers are listed from highest to lowest priority. Technically, they are applied in reverse
  # order: The provider with the highest priority is applied last, so it can overwrite any previously applied curations.
  # packageCurationProviders:
  # - type: DefaultFile
  # - type: DefaultDir
  # - type: File
  #   id: SomeCurationsFile
  #   options:
  #     path: '/some-path/curations.yml'
  #     mustExist: true

  severeIssueThreshold: ERROR
  severeRuleViolationThreshold: ERROR

  analyzer:
    allowDynamicVersions: true

    # A list of enabled package managers.
    enabledPackageManagers: [SpdxDocumentFile, Unmanaged]

    # A flag to control whether excluded scopes and paths should be skipped during the analysis.
    skipExcluded: true
  
  # downloader:
  #   allowMovingRevisions: false

  #   # Only used if the '--license-classifications-file' option is specified.
  #   includedLicenseCategories:
  #     - 'category-a'
  #     - 'category-b'

  #   # A flag to control whether excluded scopes and paths should be skipped during the download.
  #   skipExcluded: true

  #   sourceCodeOrigins: [VCS, ARTIFACT]

  scanner:
    # skipConcluded: true
    # skipExcluded: true

    archive:
      enabled: true

      fileStorage:
        localFileStorage:
          directory: /project/.ort/scanner/archive
          compression: false

    createMissingArchives: false

    # Map scanner license findings to valid SPDX licenses. Note that these mappings are only applied in new scans,
    # stored scan results are not affected.
    # detectedLicenseMapping:
    #   BSD (Three Clause License): 'BSD-3-clause'
    #   LicenseRef-scancode-generic-cla: 'NOASSERTION'

    fileListStorage:
      fileStorage:
        localFileStorage:
          directory: /project/.ort/scanner/file-lists
          compression: false

    config:
      # # A map from scanner plugin types to the plugin configuration.
      # ScanCode:
      #   options:
      #     # Command line options that affect the ScanCode output. If changed, stored scan results that were created with
      #     # different options are not reused.
      #     commandLine: '--copyright --license --info --strip-root --timeout 300'

      #     # Command line options that do not affect the ScanCode output.
      #     commandLineNonConfig: '--processes 4'

      #     # Use per-file license findings instead of per-line ones.
      #     preferFileLicense: false

      FossId:
        options:
          serverUrl: 'https://rb-fossid.de.bosch.com/XC_ADDA/'

          namingProjectPattern: '$Var1_$Var2_$Var3'
          namingScanPattern: '$Var1_$Var2_$Var3_#projectName_#currentTimestamp'
          namingVariableVar1: XC_AN
          namingVariableVar2: PK
          namingVariableVar3: GEN3

          waitForResult: true

          keepFailedScans: false
          deltaScans: true
          deltaScanLimit: 10

          detectLicenseDeclarations: true
          detectCopyrightStatements: true

          timeout: 60

          # urlMappingExample: "https://sourcecode.socialcoding.bosch.com/scm/pk(?<repoPath>.*) -> ssh://git@sourcecode.socialcoding.bosch.com:7999/pk${repoPath}"

        secrets:
          user: lzm2fe
          apiKey: mecCLcCK7WAOrXAaoeYDROtGjKb5Aqr3CHsxEb43jE

    storages:
      local:
        backend:
          localFileStorage:
            directory: /project/.ort/scanner/results
            compression: false

    # Storage readers are listed from highest to lower priority, i.e. the first match wins.
    storageReaders: [local]

    # For storage writers no priority is implied by the order; scan results are stored for all writers.
    storageWriters: [local]

    ignorePatterns: ['**/META-INF/DEPENDENCIES']

    provenanceStorage:
      fileStorage:
        localFileStorage:
          directory: /project/.ort/scanner/provenance
          compression: false

  reporter:
    config:
      FossId:
        options:
          serverUrl: 'https://rb-fossid.de.bosch.com/XC_ADDA/'
        secrets:
          user: lzm2fe
          apiKey: mecCLcCK7WAOrXAaoeYDROtGjKb5Aqr3CHsxEb43jE

  # notifier:
  #   mail:
  #     hostName: 'localhost'
  #     username: user
  #     password: password
  #     port: 465
  #     useSsl: true
  #     fromAddress: 'no-reply@oss-review-toolkit.org'
